### ISSUE TITLE
Put Behind NGINX reverse proxy

### ISSUE THREAD

**Issue by 12nick12** [TwanoO67/plex-web-downloader#1]
Could I have your help editing the code to add a url_base? Also would I be able to also upload this to my github, but I've translated everything to english

**Comment by TwanoO67** [comment]
Hello,

Url are relatives in templates so why do you need to force an url_base?
For the translation in english i wonder if jade template provide a i18n principle.
If so we could use that...

**Comment by TwanoO67** [comment]
Maybe the use of i18next.com would be a nice approach for the problem...

**Comment by 12nick12** [comment]
i was able to use English.json and then I just changed all french to english. The reason I want URL Base is for nginx subfolder reverse proxy.

**Comment by TwanoO67** [comment]
Ok, Can you link what you already did so i can test in the same condition as you ?

**Comment by 12nick12** [comment]
Here is the git that I've made. It may not be perfect. This is the first time I've used github before https://github.com/12nick12/pwd If you're not OK with me using your stuff just let me know

**Comment by 12nick12** [comment]
I was able to get everything switched over to a base url. Thank you for creating such an awesome piece of software. Is it ok if I keep mine up on github?

**Comment by TwanoO67** [comment]
Hello @12nick12

Sharing is what github is meant to ;)
Of course you can keep yours on github too.

But in order to be able to follow next evolution of the software, you should rather make a "fork". 
So both project will share their common git history and will automatically be connected one to another.

If you dont know how to do that:
- first click on my repo on the fork button
- this will create a copy with the same name, but in you repo, keeping the history of commits
- next you can git clone your repo on your computer
- make your modification and commit them (at that step you can simply copy/past your code over mine, only the mosification will be recorded)

Once the fork is created like that, you will be able to do:
- merge request, if you want your code to update my repo
- rebase, if you want my new update on your code

**Comment by 12nick12** [comment]
Thank you for walking me thru that. I officially forked your repo.
